### ISSUE TITLE
Rename example output figures to benchmark-example.png and performance-example.png

### ISSUE THREAD

**Issue by zenalapp** [SchlossLab/mikropml-snakemake-workflow#2]
So that when you clone the repo it will actually run ML on everything, rather than just render the report.

@kelly-sovacool does this make sense?

**Comment by kelly-sovacool** [comment]
Yep, sounds good. Already renamed the report based on this feedback from @tomkoset. All the example output files should have -example before the extension.

**Comment by zenalapp** [comment]
Oops I made changes but can't push. @kelly-sovacool can you give me permission or should I fork the repo?

**Comment by kelly-sovacool** [comment]
invitation sent!
