### ISSUE TITLE
Make changing hyperparameters easier

### ISSUE THREAD

**Issue by zenalapp** [SchlossLab/mikropml-snakemake-workflow#6]
The way I did it is just add them to the ML script, but then it re-runs all of the models even if you didn't change the hyperparameters. One idea:

- Create a rule that generates a separate R data file for each model being used. The R data file contains a list of hyperparameters for the given model. 
    - The script takes in the preprocessed dataset, since some of the default hyperparameters are chosen dynamically. 
    - In this repo, we'll make the defaults equivalent to the default hyperparameters in `mikropml::run_ml`. 
- Users can modify the defaults for any given model in the script.
- The run_ml rule takes the hyperparameter file for the model being used.

There might be flaws to this logic because I haven't thought it out entirely...

**Comment by ykefella** [comment]
Regarding costume hyperparameters, inside the snakefile I passed a hyperparameters in a dictionary syntax.  For example, I used L2 logitic regression and random forest. ![Screen Shot 2021-08-09 at 11 47 18 AM](https://user-images.githubusercontent.com/55122158/128734934-ca590f8b-4f22-4ce4-aa40-a6a48dd4f406.png)![Screen Shot 2021-08-09 at 11 44 13 AM](https://user-images.githubusercontent.com/55122158/128734373-5a0cbb7f-2a49-401d-b4ff-92479ee5df6a.png)
Inside rule run_ml, I call the new_hp
![Screen Shot 2021-08-09 at 11 47 18 AM](https://user-images.githubusercontent.com/55122158/128734934-ca590f8b-4f22-4ce4-aa40-a6a48dd4f406.png)
However, it accepts the new hyperparameter for L2 logistic regression, but for random forest it outputs an error: 
![Screen Shot 2021-08-09 at 11 41 27 AM](https://user-images.githubusercontent.com/55122158/128733975-60185aa5-4860-4036-a52f-f2695ceae1aa.png)
But when I indicate only one model in the config.yml ml_methods to be 'rf', and change the dictionary to have only mtry,  it works. 
Do you have any suggestions to the way I have approached it? or Do you have an example to the logic you had outlined above?
