### ISSUE TITLE
Error in job combine_results while creating output file results/performance_results.csv

### ISSUE THREAD

**Issue by ykefella** [SchlossLab/mikropml-snakemake-workflow#8]
I run the initial testing of mikropml-snakemake-workflow on my local computer with default parameters and default config file. I run snakemake on CL using four cores. It finished 37 of 43 steps (86%) and after that it halted. When I open log/combine_results_performance.txt, I see the attached message;
![Screen Shot 2021-07-29 at 9 13 46 AM](https://user-images.githubusercontent.com/55122158/127498289-7d4fb735-4289-4640-9d58-45ddf8564788.png)

**Comment by BTopcuoglu** [comment]
@ykefella Which steps failed, could you give us a list of those?

**Comment by ykefella** [comment]
The following jobs failed;
- rule combine_results
- rule plot_performance
- rule plot_hp_performance ( for random forest only)
- rule plot_benchmarks
- rule render_report
- rule clean

**Comment by ykefella** [comment]
source("code/log_smk.R")
library(tidyverse)

snakemake@input[["csv"]] %>%
  lapply(read_csv) %>%
  **bind_rows() %>%**
  write_csv(snakemake@output[["csv"]])

Inside combine_results.R, the issue appears to come from the highlighted code above. That was modified to the following code; 
snakemake@input[["csv"]] %>%
  lapply(read_csv) %>%
  **data.table::rbindlist() %>%**
  write_csv(snakemake@output[["csv"]]) 

Now combine_result.R run as expected. 
source("https://stackoverflow.com/questions/61322131/convert-a-large-list-of-tibbles-into-a-single-tibble")

**Comment by kelly-sovacool** [comment]
`bind_rows()` from `dplyr` works for us. Perhaps you have older versions of dplyr or its dependencies installed? You could try updating dplyr or the tidyverse metapackage.
