### ISSUE TITLE
Error in job plot_benchmarks while creating output file figures/benchmarks.png

### ISSUE THREAD

**Issue by ykefella** [SchlossLab/mikropml-snakemake-workflow#9]
After modifying combine_results.R and run snakemake again, the job execution failed. The following error is printed out; 
![Screen Shot 2021-07-29 at 4 33 44 PM](https://user-images.githubusercontent.com/55122158/127561957-9a843b53-6957-4de9-85ba-6da9dcc97c62.png)

max_rass is a character type and when dividing by 1024, it throws the above error.

**Comment by kelly-sovacool** [comment]
This works for us. You should try updating dplyr or the tidyverse metapackage.
